# need super user privileges to execute the following commands
language: generic
sudo: required
services:
        - docker

before_install:        
        - docker build -t rooch/docker-react -f Dockerfile.dev .

script:
        - docker run rooch/docker-react npm run test -- --coverage



